import { builtinModules } from 'node:module';
import { defineConfig, loadEnv } from 'vite'
import { viteStaticCopy } from 'vite-plugin-static-copy'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, process.cwd(), '');

    const prod = mode === 'production';

    return {
        plugins: [
          viteStaticCopy({
            targets: [
                {
                    src: 'manifest.json',
                    dest: ''
                },
                {
                    src: 'versions.json',
                    dest: ''
                }
            ]
          })
        ],
        build: {
            outDir: env.OUTPUT_DIR ?? 'dist',
            emptyOutDir: false,
            target: "es2018",
            minify: prod,
            sourcemap: prod ? false : 'inline',
            lib: {
                entry: "src/main.ts",
                formats: ["cjs"],
                fileName: 'main',
                cssFileName: 'styles'
            },
            rollupOptions: {
                treeshake: true,
                output: {
                    entryFileNames: "main.js",
                    banner: banner
                },
                external: [
                    "obsidian",
                    "electron",
                    "@codemirror/autocomplete",
                    "@codemirror/collab",
                    "@codemirror/commands",
                    "@codemirror/language",
                    "@codemirror/lint",
                    "@codemirror/search",
                    "@codemirror/state",
                    "@codemirror/view",
                    "@lezer/common",
                    "@lezer/highlight",
                    "@lezer/lr",
                    ...builtinModules
                ]
            }
        }
    }
})